### ISSUE TITLE
Is there HTTPS support with this Driver?

### ISSUE THREAD

**Issue by TomOStewart** [PTCInc/Universal-Device-Driver-Examples#30]
I have augmented the examples for my use case but am getting a 500 error from my server with a response

 combination of host and port requires TLS

**Comment by rlabbeptc** [comment]
Hi @TomOStewart! Unfortunately, UDD does not have any TLS support, which limits it from supporting HTTPS connections at this time. The [readme](https://github.com/PTCInc/Universal-Device-Driver-Examples/tree/main/HTTP-REST) documents this as well as other limitations.

Let us know if you have any other questions.
